spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENTSERVICE
          uri: lb://STUDENTSERVICE
          predicates:
            - Path=/student/**
        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payment/**
        - id: WARDENSERVICE
          uri: lb://WARDENSERVICE
          predicates:
            - Path=/warden/**
        - id: LEAVESERVICE
          uri: lb://LEAVESERVICE
          predicates:
            - Path=/leave/**
server:
  port: 8084
#EUREKA CONFIGURATION

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry : true
    register-with-eureka : true
    service-url:
      defaultZone : http://localhost:8761/eureka/
