server:
  port: 8083

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pramodpatil7058/Hostel-Config-Server
          ignore-local-ssh-settings: true
          skip-ssl-validation: true
